---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/categories":
    get:
      summary: Returns categories and/or subcategories
      tags:
      - Categories
      parameters:
      - name: category[type]
        in: query
        schema:
          type: string
          enum:
          - all
          - category
          - subcategory
      - name: page
        in: query
        schema:
          type: integer
          minimum: 1
      responses:
        '200':
          description: categories or subcategories returned
        '400':
          description: invalid type
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
